name: Deployment

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy-release-push:
    name: Deploy on release or push to main
    runs-on: ubuntu-latest
    steps:
      - name: Testing if the action is working
        run: echo "Hello World"
