name: Deploy to AWS

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Deploying to AWS"
          cd ~
          echo "${{ secrets.SSH_KEY }}" > server.pem
          chmod 400 server.pem
          # connect to the user with our confirmation
          ssh -o "StrictHostKeyChecking no" -i server.pem ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}}
          ls
          cd project
          ls 
      