name: Deploy on release

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy only on main branch
    runs-on: ubuntu-latest
    # check the branch is main
    steps:
      - name: Testing if the action is working
        run: echo "Release is published"
      
      - name: Print the tag name
        run: |
          echo "github.ref is ${{ github.ref }}"
          echo "github.ref_name is ${{ github.ref_name }}"
          echo "github.ref_type is ${{ github.ref_type }}"
          echo "github is ${{ toJSON(github) }}"
          echo "__version__ = ${{ github.ref_name }}" > __version__.py
          cat __version__.py
